version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: whiteboard-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: whiteboard
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - whiteboard-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: whiteboard-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whiteboard-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: whiteboard-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: mongodb://admin:password@mongodb:27017/whiteboard?authSource=admin
      REDIS_URL: redis://redis:6379
      CLIENT_URL: http://localhost:3000
      JWT_SECRET: dev-jwt-secret-change-in-production
      JWT_REFRESH_SECRET: dev-refresh-secret-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - whiteboard-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: whiteboard-client
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_SOCKET_URL: ws://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - whiteboard-network

volumes:
  mongodb_data:
  redis_data:

networks:
  whiteboard-network:
    driver: bridge
