services:
  - type: web
    name: whiteboard-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE_TIME
        value: 15m
      - key: JWT_REFRESH_EXPIRE_TIME
        value: 7d
      - key: LOG_LEVEL
        value: info
      - key: CLIENT_URL
        value: https://your-frontend-domain.netlify.app

databases:
  - name: redis
    databaseName: whiteboard-cache
    user: default
